name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.1.app/Contents/Developer

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Test
      run: xcodebuild -workspace DrinkUp.xcworkspace -scheme DrinkUp -destination "platform=iOS Simulator,OS=14.1,name=iPhone 12 Pro Max" -enableCodeCoverage YES -resultBundlePath .build/Coverage CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build test
    - name: Code coverage
      run: xcrun xccov view --report --files-for-target DrinkUp.app .build/Coverage.xcresult
    - name: Code Coverage
      run: bash <(curl -s https://codecov.io/bash) -J 'DrinkUp'
