name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.1.app/Contents/Developer

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for SwiftLint (Only files changed in the PR)
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict
      env:
        DIFF_BASE: ${{ github.base_ref }}
    - name: GitHub Action for SwiftLint with --strict
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict

  Build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Test
      run: xcodebuild -workspace DrinkUp.xcworkspace -scheme DrinkUp -destination "platform=iOS Simulator,OS=14.1,name=iPhone 12 Pro Max" -enableCodeCoverage YES -resultBundlePath .build/Coverage CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build test
    - name: Code coverage
      run: xcrun xccov view --report --files-for-target DrinkUp.app .build/Coverage.xcresult
    - name: Codecov
      run: bash <(curl -s https://codecov.io/bash) -J 'DrinkUp'
